### ISSUE TITLE
Stand-Up Tasks

### ISSUE THREAD

**Issue by risatino** [risatino/seadogz#3]
#### Story
These are tasks we set up on 7/7/2018, etc.

---
#### What does done look like?
This will likely change as we have more stand-up sessions.

---
#### Tasks
- [x] List out tasks and amend details as we do our first stand-up
- [x] Discuss - sci-kit learn ideas
- [x] Team - Research Load Data For Basketball players
- [x] David - Cleaning Data (a.k.a. Excel Magic)
- [x] David - Format Player ID's with the stats data
- [x] David - Web Scraping Tables
- [x] Natalie - Pulling Data + Access to Catapult Data
- [x] Natalie - Demographics, Injury Data, etc.
- [x] Brooks - Tableau Dashboard Work + Research Visuals
- [x] Brooks - Excel Workbook: Sorting/Merging/Collecting
- [x] Risa - Flask + Plotly + set-up recycled template from last project
- [x] Risa - Embed Tableau charts/dashboards into Flask app
- [x] Team - Jupyter Notebooks / cleaning CSVs / Pandas / Charts 
- [x] Team - Use sci-kit learn to show a regression (most likely logistic)

---
#### Ideas/Brainstorming
* scikit learn
* PlotlyJS, Flask, Demographics (mapbox-leaflet/carto)
