### ISSUE TITLE
Research Accessible NCAA API Data + Compare With Other Reliable Resources

### ISSUE THREAD

**Issue by risatino** [risatino/seadogz#4]
#### Story
Some data is not easy to access with the API or needs a second source. For example for wins and losses, we had to do research to check it with our provided data.

#### What does done look like?
We have more than one resource for data we use. We should not just rely on provided data as a self-check.

#### Tasks
- [x] Google: Wins and Losses
- [x] List other resources we could use for our dataset

#### Include:
- [x] Stats
- [x] Science For Sports

**Comment by risatino** [comment]
This has been included into our CSV and Tableau data analysis.
