### ISSUE TITLE
Sci-kit Learn

### ISSUE THREAD

**Issue by risatino** [risatino/seadogz#6]
#### Story
Incorporate ML/Sci-kit Learn into data sets.

---
#### What does done look like?
Scikit Learn is being used.

---
#### Tasks
- [x] Choose a ML tool, scikit learn
- [x] Plan/Outline tasks
- [x] Discuss with team what data we will use scikit learn on
- [x] Create Training & Test models with datasets (see examples in data_analysis.ipynb)
- [x] Look at Comparison with Wearable Tech + Stats: no corrolation (will look at it again)
- [x] Regression analysis using sci-kit learn
- [x] Discuss how might include our Training & Test models into our story-telling

#### Impediments:
- [x] merging datetime columns (format a new column)
- [x] datetime with linear regression (try onehotcoding in scikit learn)
