### ISSUE TITLE
Tableau: Acute to Chronic Data Comparisons

### ISSUE THREAD

**Issue by risatino** [risatino/seadogz#9]
#### Story
Tableau: Visual Discovery with Acute to Chronic Data Sets + Injury + Wins/Losses

---
#### What does done look like?
Create variations of graphs to compare data sets.

---
#### Tasks
- [x] Look at dashboard to see what types of graphs make sense
- [x] Brooks - Create our own analysis using Tableau
- [x] Use embedded Tableau (iframes)
- [x] TEAM tableau/pandas/jupyter notebook - Display Acute vs Chronic Load Comparisons
- [x] TEAM tableau/pandas/jupyter notebook/scikit learn - Considerations Tab: Failed Attempts of Data Analysis/ML
- [x] TEAM - Write Content for Failed Attempts from Data Analysis/ML
- [x] TEAM tableau/pandas/jupyter notebook - Choose ones to display on Flask app
